In [1]:
import numpy as np

In [2]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [3]:
def derSig(z):
    return sig(z)* (1 - sig(z))

In [4]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0, 0, 0, 1]]).T
cols = X.shape[1]
cols

2

In [5]:
print("Enter number of hidden layer: ")
n = int(input())

Enter number of hidden layer: 
3


In [6]:
hidden_layer_weights = []
hidden_layer_biases = []
for i in range(n):
    wh = 2 * np.random.random((cols, cols)) - 1
    bh = 2 * np.random.random((1, cols)) - 1
    hidden_layer_weights.append(wh)
    hidden_layer_biases.append(bh)
    
wout = 2 * np.random.random((cols, 1)) - 1
bout = 2 * np.random.random((1,1)) - 1

In [7]:
wout

array([[0.51838287],
       [0.39739232]])

In [8]:
def forward(x, hidden_layer_weights, wout, hidden_layer_biases, bout):
    current_output = x
    for i in range(n):
        current_HL_weights = hidden_layer_weights[i]
        current_HL_input = np.dot(current_output, current_HL_weights) + hidden_layer_biases[i]
        current_HL_output = sig(current_HL_input)
        current_output = current_HL_output
    
    output_layer_input = np.dot(current_output, wout) + bout
    final_output = sig(output_layer_input)
    return final_output

In [9]:
def train(x, y, hidden_layer_weights, wout, hidden_layer_biases, bout, epochs, lr):
    for itr in range(epochs):
        #forward propagation
        hidden_layer_outputs = []
        hidden_layer_inputs = []
        current_output = x
        for i in range(n):
            current_HL_weights = hidden_layer_weights[i]
            current_HL_input = np.dot(current_output, current_HL_weights) + hidden_layer_biases[i]
            current_HL_output = sig(current_HL_input)
            hidden_layer_inputs.append(current_HL_input)
            hidden_layer_outputs.append(current_HL_output)
            current_output = current_HL_output

        output_layer_input = np.dot(current_output, wout) + bout
        final_output = sig(output_layer_input)
        
        #back propagation
        first_two_prod_terms = []
        first_term_output = final_output - y
        second_term_output = derSig(output_layer_input)
        first_two_output = first_two_product = first_term_output * second_term_output
        
        weights = wout
        for i in range(n):
            first_term_hidden_layer = np.dot(first_two_product, weights.T)
            second_term_hidden_layer = derSig(hidden_layer_inputs[n-i-1])
            first_two_product = first_term_hidden_layer * second_term_hidden_layer
            first_two_prod_terms.append(first_two_product)
            weights = hidden_layer_weights[n-i-1]
            
        first_two_prod_terms.reverse()
        changes_wt_hidden_layers = []
        changes_biases_hidden_layers = []
        curr_output = x
        for i in range(n):
            changes_wh = np.dot(curr_output.T, first_two_prod_terms[i])
            changes_bh = np.sum(first_two_prod_terms[i], axis = 0)
            changes_wt_hidden_layers.append(changes_wh)
            changes_biases_hidden_layers.append(changes_bh)
            curr_output = hidden_layer_outputs[i]
        changes_wout = np.dot(curr_output.T, first_two_output)
        changes_bout = np.sum(first_two_output, axis = 0)
        
        for i in range(n):
            hidden_layer_weights[i] = hidden_layer_weights[i] - lr * changes_wt_hidden_layers[i]
            hidden_layer_biases[i] = hidden_layer_biases[i] - lr * changes_biases_hidden_layers[i]
        wout = wout - lr * changes_wout
        bout = bout - lr * changes_bout
        
    return hidden_layer_weights, wout, hidden_layer_biases, bout

In [10]:
hidden_layer_weights, wout, hidden_layer_biases, bout = train(X, Y, hidden_layer_weights, wout, hidden_layer_biases, bout, 10000, 1)

In [11]:
forward(X, hidden_layer_weights, wout, hidden_layer_biases, bout)

array([[0.00517004],
       [0.00680352],
       [0.00687705],
       [0.99176491]])

In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.sum(a, axis = 0, keepdims=True)
b,b.shape

(array([[5, 7, 9]]), (1, 3))

In [13]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
wh = 2 * np.random.random((2, 2)) - 1
wout = 2 * np.random.random((2, 1)) - 1
bh = 2 * np.random.random((1,2)) - 1
bout = 2 * np.random.random((1,1)) - 1
ho = sig(np.dot(X, wh)+bh)
sig(np.dot(ho, wout) + bout)

array([[0.55839511],
       [0.55678626],
       [0.5485577 ],
       [0.54739079]])